name: miswag
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it:
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.8
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  bloc: ^8.1.4
  internet_connection_checker_plus: ^2.7.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/image/
