// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0C3hbiZYd71lqqoAiAmNWn6JdtBhLGcw',
    appId: '1:129572857135:web:8164f13f75ba6e3aed2dda',
    messagingSenderId: '129572857135',
    projectId: 'miswag-clone',
    authDomain: 'miswag-clone.firebaseapp.com',
    storageBucket: 'miswag-clone.firebasestorage.app',
    measurementId: 'G-HMM6SB3QC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlP-QSXpXakQ2wlaPlIYKdXI9ZRjSgp4',
    appId: '1:129572857135:android:5e2e7dbc68ffc8d2ed2dda',
    messagingSenderId: '129572857135',
    projectId: 'miswag-clone',
    storageBucket: 'miswag-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-ytVJbgY3cmfVp-tWGYcYNnIk4nIGs4',
    appId: '1:129572857135:ios:5ea5d2ecf3658afded2dda',
    messagingSenderId: '129572857135',
    projectId: 'miswag-clone',
    storageBucket: 'miswag-clone.firebasestorage.app',
    iosBundleId: 'com.example.miswag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-ytVJbgY3cmfVp-tWGYcYNnIk4nIGs4',
    appId: '1:129572857135:ios:5ea5d2ecf3658afded2dda',
    messagingSenderId: '129572857135',
    projectId: 'miswag-clone',
    storageBucket: 'miswag-clone.firebasestorage.app',
    iosBundleId: 'com.example.miswag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0C3hbiZYd71lqqoAiAmNWn6JdtBhLGcw',
    appId: '1:129572857135:web:38cfa9d196011baeed2dda',
    messagingSenderId: '129572857135',
    projectId: 'miswag-clone',
    authDomain: 'miswag-clone.firebaseapp.com',
    storageBucket: 'miswag-clone.firebasestorage.app',
    measurementId: 'G-60VGY4LW0Z',
  );
}
